version: '3'

services:
  app:
    build: .
    tty: true
    container_name: go_task
    volumes:
    - .:/go/src/task/
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./sqls/init:/docker-entrypoint-initdb.d
    container_name: go_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always

volumes:
  mysql_data: